# GitHub Actions workflow for test, build, tag, and deploy
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run tests
        run: |
          if [ -f test_fake_log_gen.py ]; then python test_fake_log_gen.py; else echo 'No tests found.'; fi

      - name: Build artifact
        run: |
          mkdir -p dist
          cp FakeLogGen.py dist/

      - name: Tag release
        if: github.ref == 'refs/heads/main'
        id: tag
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M%S')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $VERSION
          git push origin $VERSION

      - name: Deploy (placeholder)
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'Deploy step goes here.'
